In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('/Users/coreenjohn/Downloads/tree-heights.csv', index_col=0)

#Melt the document for tidy data
df = df.melt(var_name='species', value_name='height')
df.dropna(inplace=True)

#Display the data 
df

    species  height
0       oak   18.85
1       oak   31.93
2       oak   30.25
3       oak   24.32
4       oak   18.25
5       oak   30.01
6       oak   22.77
7       oak   22.55
8       oak   25.72
9       oak   19.56
10      oak   22.38
11      oak   23.02
12      oak   25.35
13      oak   18.80
14      oak   24.78
15      oak   25.54
16      oak   30.06
17      oak   17.05
18      oak   25.20
19      oak   19.01
20      oak   22.24
21      oak   25.45
22      oak   31.62
23      oak   29.04
24      oak   19.79
25      oak   22.06
26      oak   29.99
27      oak   20.68
28      oak   21.75
29      oak   24.60
..      ...     ...
296  willow    5.85
297  willow    5.33
298  willow    8.49
299  willow   15.48
300  willow    6.28
301  willow   13.10
302  willow    6.59
303  willow   16.45
304  willow    8.71
305  willow   14.58
306  willow    9.60
307  willow    7.77
308  willow    9.88
309  willow    6.44
310  willow   11.08
311  willow    7.48
312  willow   12.19
313  willow   12.76
314  willow   10.78
315  willow    8.28
316  willow   12.25
317  willow   12.22
318  willow    9.16
319  willow   13.40
320  willow   16.46
321  willow   11.51
322  willow    7.89
323  willow    9.76
324  willow    4.51
325  willow   13.37

[296 rows x 2 columns]